### ISSUE TITLE
[BUG] ConnectionHiddenCheckClient client = calcFactory.Create();     Time out Exception

### ISSUE THREAD

**Issue by paolobia** [idea-statica/ideastatica-public#337]
Hi,

intalldir = "C:\\Program Files\\IDEA StatiCa\\StatiCa 23.0"
ConnHiddenClientFactory calcFactory = new ConnHiddenClientFactory(intalldir);
ConnectionHiddenCheckClient client = calcFactory.Create();

C:\\Program Files\\IDEA StatiCa\\StatiCa 23.0\\IdeaStatica.Plugin.dll : 23.0.5.1256

System.TimeoutException: 'Timeout the process 'C:\Program Files\IDEA StatiCa\StatiCa 23.0\IdeaStatiCa.ConnHiddenCalculator.exe' doesn't set the event 'IdeaStatiCa.ConnHiddenCalculator-22288' in 40 s (limit is 40000 s)'

help!!!

**Comment by nathanlukeIDEA** [comment]
Hi @paolobia, are you using the NuGet package to reference IdeaStatiCa.Plugin?

**Comment by paolobia** [comment]
No, I add a reference from  C:\Program Files\IDEA StatiCa\StatiCa 23.0

**Comment by nathanlukeIDEA** [comment]
You will likely get better results using the NuGet, this is the recommended way.

**Comment by paolobia** [comment]
Hi, 
I have installed 
C:\Program Files\IDEA StatiCa\StatiCa 23.0   (23.0.5.1256) and 
C:\Program Files\IDEA StatiCa\StatiCa 22.1   (22.1.6.0478)

using NuGet version of  IdeaStatiCa.Plugin 23.0.5.1256
the 
`ConnectionHiddenCheckClient client = calcFactory.Create();`
run good with 22.1.6.0478 but still timeout with 23.0.5.1256
:-(

**Comment by nathanlukeIDEA** [comment]
Hi @paolobia, thank you we are fixing now and will let you know.

**Comment by nathanlukeIDEA** [comment]
@paolobia this should now be working with latest release.

**Comment by gerso-magro** [comment]
@nathanlukeIDEA, I am using idea statica 24.0.3.1498 and I still get the runtime error when running this code:
ConnectionHiddenCheckClient client = calcFactory.Create();

Help please
